### ISSUE TITLE
Step 1 needed?

### ISSUE THREAD

**Issue by kenny-bui** [OfficeDev/Microsoft-Teams-App-Reflect#11]
Could you verify that the step 1 is needed? I don't see where info in step 1 being used anywhere throughout the process.

**Comment by Darren-Austin** [comment]
Yes, Step 1 is where you generate the Application ID and App Secret that you use in Step 3 when filling out the Bot ID and Bot Client Secret fields in the form for deploying the new template.

**Comment by kenny-bui** [comment]
You mean Bot ID & Bot Client Secret? (and these are created in step 2) I don't see fields for Application ID & App Secret(attached)

Technically, how many 1 or 2 apps do I need to registered/create?

Step 2: Create an app registration
Let's create an app registration for the bot. **This step will generate an Application ID and an App Secret that we will use in the next step** when building the template.
![image](https://user-images.githubusercontent.com/65940735/90693148-2de9f580-e22b-11ea-86d5-bf85d7f85cec.png)

**Comment by pezevallaymar** [comment]
Hi, could you please confirm (or clarify in the documentation-Deployment guide) which app to use when in the process? It's unclear. there are several references through the steps and it would be advisable to clarify in each Step to which app you are referring to (is it the messaging Extension Teams app or the Bot App?)  (Step 3, Step 5.5, Step 7.4)

Thank you

**Comment by pezevallaymar** [comment]
> Yes, Step 1 is where you generate the Application ID and App Secret that you use in Step 3 when filling out the Bot ID and Bot Client Secret fields in the form for deploying the new template.

But in the deployment guide mentions Step 2. It would be great to specify in the doc, which AppID/Secret is referred throughout the process.

**Comment by Darren-Austin** [comment]
Hi @kenny-bui - we just updated the deployment guide and the ARM template in the source code.  I think you'll find the process to be much improved. Thanks for your patience and feedback.
