### ISSUE TITLE
Step 5. Where do I get the Microsoft App ID and MicrosoftAppPassword

### ISSUE THREAD

**Issue by pezevallaymar** [OfficeDev/Microsoft-Teams-App-Reflect#14]
Hi team. In step 5, can you explain where do I get the information of MicrosoftAppId and MicrosoftAppPassword?

Entering fields in in appsettings.json file:

Baseuri: URL in the app service (Go to resource group created earlier, click on app service resource created).
**MicrosoftAppId: Microsoft App ID (this is available in bot service).
MicrosoftAppPassword: key available inside the manage bot id (this is available in bot service).**
InstrumentationKey: Application Insights Instrumentation key (this is available in bot service).
StorageAccountConnectionString: Go to resource group created on the right, for the resources created.

**Comment by Darren-Austin** [comment]
Hi @pezevallaymar - we have been working on an improved deployment process to reduce confusion in the deployment. 
 The deployment guide and the ARM template in the source code have both just been updated with the new streamlined process.  Please try to deploy again with this new method.
