### ISSUE TITLE
Not Able to Upload the final Manifest to Microsoft Teams

### ISSUE THREAD

**Issue by bantikant** [OfficeDev/Microsoft-Teams-App-Reflect#22]
Hi All, 
I followed the deployment guide on 30Sep20 but my final upload to the teams (via upload custom app in teams on-prem console) is failing. I am mentioning the error message below.
![image](https://user-images.githubusercontent.com/24382327/94828764-dc807900-041a-11eb-9d6e-0f0435bc177f.png)

also, getting below error message

Error while reading manifest.json: Invalid value(s) specified for id: "{{yTKAOEwoFUWl6jEPy3-XmQ}}"
 Invalid GUID specified for bots[0].botId: ""
 Invalid GUID specified for composeExtensions[0].botId: ""

please help........

**Comment by Darren-Austin** [comment]
Hi @bantikant !  Thanks for including the error message.  Remove the curly brackets in the ID field and try to upload to Teams again.  Also, it looks like maybe you didn't include the GUID for the Application ID in lines 31 and 41 so make sure you edit those lines with the Application ID you created in Step 1. Make sure that no brackets appear in any of the ID fields (lines 5, 31, and 41).  

The template manifest file has those curly brackets included but they should be removed when generating the GUID.  I'll update the deployment guide to make a note of this so it's more clear.  I appreciate your catching this.  Let me know if you are successful with the upload after removing those curly brackets.

**Comment by bantikant** [comment]
Thanks Darren, its fixed now and i am able to add the app in Teams. 

Much Appreciated

Ravi
