### ISSUE TITLE
Template deployment screenshot

### ISSUE THREAD

**Issue by xrysmu-bsd** [OfficeDev/Microsoft-Teams-App-Reflect#24]
Small thing, but in the section where you show creating the custom template you show the web app service name it has spaces in it, but Azure doesn't accept spaces in the name.  It generated an error for me and I had to look at the error to see the issue (forgot it didn't allow that).
Chris

**Comment by Darren-Austin** [comment]
Good catch!  I'll make a note of that in the deployment guide now and work on getting a replacement image for that step.  Thanks for the heads up.
