### ISSUE TITLE
new install says - Unable to reach app. Please try again.

### ISSUE THREAD

**Issue by bickyz** [OfficeDev/Microsoft-Teams-App-Reflect#29]
Hi,
I have followed the deployment guide from here https://github.com/OfficeDev/Microsoft-Teams-App-Reflect/wiki/Reflect-Deployment-Guide.

Within Teams when I click Reflect icon a pop-up box says "Unable to reach app. Please try again.". I am not sure what have I missed, Any help on this will be much appreciated, thank you.

![MSTeams-23Oct20-01](https://user-images.githubusercontent.com/6534923/96969150-ea9d5300-1509-11eb-8ec8-8def5ac1b156.JPG)

**Comment by Darren-Austin** [comment]
Hi @bickyz - check out the thread in [issue 13](https://github.com/OfficeDev/Microsoft-Teams-App-Reflect/issues/13) for troubleshooting steps on this issue.

**Comment by bickyz** [comment]
thank you Darren, followed your video to re-do it which works now.
https://www.youtube.com/watch?v=qawolLEf0Ts
