### ISSUE TITLE
App doesn't create polls

### ISSUE THREAD

**Issue by ebahsadmin** [OfficeDev/Microsoft-Teams-App-Reflect#34]
I was able to successfully upload the app into a Team using the client upload custom app option, however when attempting to create a Reflect poll and selecting the Confirm button, it shows a loading symbol before the window disappears. The poll is not added to the chat or the Team conversation tab.
![Reflect App Confirm](https://user-images.githubusercontent.com/46037048/101851207-da6b3100-3ba6-11eb-80af-3d60badcde9a.png)
![Reflect App loading](https://user-images.githubusercontent.com/46037048/101851382-2c13bb80-3ba7-11eb-808a-953d80948482.png)

**Comment by ebahsadmin** [comment]
Edit: I've been able to rectify this using the advice on one of the closed issue threads. It seems as though you must have the app registration supported account types set to Multiple organizations as opposed to single tenant?

**Comment by Darren-Austin** [comment]
Hi @ebahsadmin. That is correct.

**Comment by ebahsadmin** [comment]
Thank you for confirming Darren, are you guys able to update the documentation with this?
