### ISSUE TITLE
Does not work for education account

### ISSUE THREAD

**Issue by HardyKrause** [OfficeDev/Microsoft-Teams-App-Reflect#6]
Unfortunately this great feature does not work with the free O365 (M365) version. It is not allowed to create ressources. You should give a hint. This saves hours of searching where the problem arises from.
Hardy

**Comment by Darren-Austin** [comment]
Hi HardyKrause.  Apologies for the difficulty.  Can you be specific about where you ran into a problem with deployment?  Reflect does require an Azure account capable of creating new Resources.  I believe this is possible with the free Azure trial but will confirm that and update with a notice if that is not the case.
