### ISSUE TITLE
while installing Microsoft-Teams-App-Reflect I can not find input for providing github URL

### ISSUE THREAD

**Issue by mshukurlu** [OfficeDev/Microsoft-Teams-App-Reflect#7]
Hi friends!,

I want to add Microsoft Teams App Reflect to my system. I have rich till Step 3 Bu then I want to pass step 3.8 then I can not find the proper place to add github URL  as mentioned on documentation. Please look at step 8.
![Screenshot_2](https://user-images.githubusercontent.com/11161906/90146498-29888d00-dd92-11ea-8796-72edf66b816d.png)

I looked it on Chanells => Microsoft Teams => Edit section

Please help me .

Adittionally if you have any other installation guide (or videocast) please share them with me.

Thanks In advance!

**Comment by Darren-Austin** [comment]
Hi. Thank you for the feedback.  That step can be better clarified.  I will update the Deployment Guide now with better instructions.  In the meantime, the place to enter that URL is in Visual Studio 2019.  Here are the revised instructions for steps 8 and 9:

8. Open Visual Studio 2019 and select Team Explorer from the View menu.
9 In the Team Explorer window select Manage Connections (appears as a green icon in the top menu bar)
10. Select Clone and enter the URL for the Reflect GitHub repo (https://github.com/OfficeDev/Microsoft-Teams-App-Reflect.git) as the repo to be cloned and choose the location where you want the local repo to be saved.
11. Select Clone.

**Comment by mshukurlu** [comment]
@Darren-Austin thank you much!,

I have pass the step after reading your updated guide,

After I upload the package to my team I faced an error "Unable to reach app. Please try again." I think there are some issues filling some inputs . I started from initial.While working on **Custom deployment** section I faced some inputs 
![Screenshot_2](https://user-images.githubusercontent.com/11161906/90397537-0d922d80-e0a9-11ea-850a-2cfddfa3a39d.png)

On the documentation there no more inormation about those inputs for example I can not understand what is App Service Plan,
Bot Servicesname,Storage Account Name,Web App Service,App Insights,App Insights Components 
Currently I faced validation errors when I left them blank.Please share your experiences about those, how can I add them proper way?. Any video tutorial related this would be good.

Thanks in Advance.

**Comment by v-visnal** [comment]
Thanks for the feedback. We will add more details to make the fields understandable. Regarding App service plan you can provide a plan like for example "standard", for now it does not make any impact in future you can categorize people to use the app based on the plan. For the non-mandatory fields, please provide reflectapp as default name as they are all the resource names and not going to effect anything for now :). We will update the template to have those default value to remove this confusion for the users.

**Comment by mshukurlu** [comment]
@v-visnal thank you for support!,

I have upload the package but I faced an error it says "Team" - can not reach to the app.

![Screenshot_3](https://user-images.githubusercontent.com/11161906/90863028-63afeb00-e39f-11ea-96f8-e25a4da92c15.png)

How can I know the reason of this problem?

Can I see logs ?.

Please share your advices, Thanks you much!

Note: any slack , discord or microsoft team chanel would be great for communication and supporting community.

**Comment by mshukurlu** [comment]
@v-visnal I dont know why but several times I could not get success.
I think may be not good familarity with microsoft products tend me to fail.
It would be great a good video which explain everything related this package. May be I am getting some steps wrong.
For example I think while editing appsettings.json file I replace {{new GUID}} and {{bot_id}} with APP ID .

I see on the step 2 We need to create the second app. If I need to replace {{new GUID}} with APP ID which is the one?

The best way to reaching me I think is skype or email(or your suggest).If you wish we can make conversation via one of them but it would be great creating microsoft teams group or slack for this community.

**Comment by kriszentner** [comment]
I'm seeing the same issue when attempting to deploy: "Unable to reach app. Please try again.". Some debug, and test steps would be great to test the functionality of the components deployed.

I'm wondering if the manifest.json should have a link back to one of the app services created in the doc?  This app looks cool, but the deployment instructions could probably be tidied up a bit. I would be even more awesome if the deployment instructions didn't require VS2019 as that's a heavy requirement for just a deploy.

Let me know if I should create a new issue, or otherwise feel free and ping me internally.

**Comment by Darren-Austin** [comment]
Hi @kriszentner - we just updated the deployment guide and the ARM template in the source code with an improved process to resolve any potential configuration issues that could be causing the issue you are reporting here.  Please try to deploy again with this new method.  It should resolve the issues you are seeing.

**Comment by Darren-Austin** [comment]
Closing issue - resolved with latest update to deployment process.

**Comment by kriszentner** [comment]
> 
> 
> Hi @kriszentner - we just updated the deployment guide and the ARM template in the source code with an improved process to resolve any potential configuration issues that could be causing the issue you are reporting here. Please try to deploy again with this new method. It should resolve the issues you are seeing.

Thanks for the reply Darren. I'll try the deploy again.
